application: gorilla-web
version: v2
runtime: go112
api_version: go1

handlers:
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/.*
  secure: always
  redirect_http_response_code: 301

- url: /static
  static_dir: static
  secure: always
  redirect_http_response_code: 301

- url: .*
  script: _go_app
  secure: always
  redirect_http_response_code: 301
